name: Base Tests
#off
on:
  push:
    branches:
      - main
      - test_specialist
      - test_master

      - dev_specialist    
      - dev_master
      
      - prod_specialist
      - prod_master
jobs:

  base-test-master-admin-elec-linux-run:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome91-ff89
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [baseTest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name:  base-test-master-admin-elec-linux-run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          record: true
          spec: cypress/e2e/build/${{ matrix.containers }}.js
          # edge, firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


name: E2E Testing
on:
  push:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      - name: Compile Cypress tests from JS to TS
        run: yarn tsc:compile
      - name: Save Cypress artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress
          if-no-files-found: error
          path: cypress/integration
  e2e_tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome91-ff89
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [baseTest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Cypress artifacts
        uses: actions/download-artifact@v2
        with:
          name: cypress
          path: cypress/integration
      - name: Cypress Test
        uses: cypress-io/github-action@v2
        with:
          record: true
          tag: ${{ matrix.containers }}
          spec: cypress/integration/${{ matrix.containers }}.js
          browser: chrome
          build: yarn workspace ${{ matrix.containers }} build:cypress
          start: yarn workspace ${{ matrix.containers }} serve
         # config: "baseUrl=http://localhost:9000"
          cache-key: node-v${{ matrix.containers }}-on-${{ runner.os }}-hash-${{ hashFiles('yarn.lock') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CIRCLECI_KEY: ${{ secrets.CIRCLECI_KEY }}
          NETLIFY_ACCESS_KEY: ${{ secrets.NETLIFY_ACCESS_KEY }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}