name: Base Tests
#off
on:
  push:
    branches:
      - main
jobs:
  directories-master-elec-linux:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    name: Run on Chrome 81
    runs-on: ubuntu-18.04
    container: cypress/browsers:node12.16.2-chrome81-ff75
    steps:
      - uses: actions/checkout@v2
      - name: Install a project with a clean slate
        run: |
          npm ci
          $(npm bin)/cypress cache path
          $(npm bin)/cypress cache list
          $(npm bin)/cypress verify

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run Cypress tests
        run: npm run test:chrome
        continue-on-error: true

      - name: Copy test execution videos
        run: |
          mkdir public
          cp -r cypress/videos public/videos
      
      - name: Merge test results into one
        run: npm run report:merge
      
      - name: Generate HTML report
        run: npm run report:generate
      
      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          publish_dir: ./public
          spec: cypress/integration/baseTest/directoriesMasterAdmin.spec.js
        
  find-master-elec-linux:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: find-master-elec-linux
        uses: cypress-io/github-action@v2
        with:
          record: true
          spec: cypress/integration/baseTest/find.spec.js
          # edge, firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    

  master-admin-elec-linux:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: master-admin-elec-linux
        uses: cypress-io/github-action@v2
        with:
          record: true
          spec: cypress/integration/baseTest/master.spec.js
          # edge, firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  mehanic-master-elec-linux:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: mehanic-master-elec-linux
        uses: cypress-io/github-action@v2
        with:
          record: true
          spec: cypress/integration/baseTest/masterMehanic.spec.js
          # edge, firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

  menu-master-elec-linux:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: menu-master-elec-linux
        uses: cypress-io/github-action@v2
        with:
          record: true
          spec: cypress/integration/baseTest/menu.spec.js
          # edge, firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
          
  ppo-master-elec-linux:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: ppo-master-elec-linux
        uses: cypress-io/github-action@v2
        with:
          record: true
          spec: cypress/integration/baseTest/ppo.spec.js
          # edge, firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     

  reports-master-elec-linux:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: reports-master-elec-linux
        uses: cypress-io/github-action@v2
        with:
          record: true
          spec: cypress/integration/baseTest/reports.spec.js
          # edge, firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

  desktopSH-master-elec-linux:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: desktopSH-master-elec-linux
        uses: cypress-io/github-action@v2
        with:
          record: true
          spec: cypress/integration/baseTest/shDesktopMasterAdmin.spec.js
          # edge, firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
  
  mobileSH-master-elec-linux:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: desktopSH-master-elec-linux
        uses: cypress-io/github-action@v2
        with:
          record: true
          spec: cypress/integration/baseTest/shMobileMasterAdmin.spec.js
          # edge, firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

  specialist-admin-elec-linux:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: specialist-admin-elec-linux
        uses: cypress-io/github-action@v2
        with:
          record: true
          spec: cypress/integration/baseTest/specialist.spec.js
          # edge, firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  start-admin-elec-linux:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: start-admin-elec-linux
        uses: cypress-io/github-action@v2
        with:
          record: true
          spec: cypress/integration/baseTest/start.spec.js
          # edge, firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  storage1-master-elec-linux:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: storage1-master-elec-linux
        uses: cypress-io/github-action@v2
        with:
          record: true
          spec: cypress/integration/baseTest/storage1.spec.js
          # edge, firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    

  storage2-master-elec-linux:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: storage2-master-elec-linux
        uses: cypress-io/github-action@v2
        with:
          record: true
          spec: cypress/integration/baseTest/storage2.spec.js
          # edge, firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
             
          