name: Base Tests
#off
on:
  push:
    branches:
      - main
jobs:

  start-admin-elec-linux:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: start-admin-elec-linux
        uses: cypress-io/github-action@v2
        with:
          record: true
          spec: cypress/integration/baseTest/start.spec.js
          # edge, firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  specialist-admin-elec-linux:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: specialist-admin-elec-linux
        uses: cypress-io/github-action@v2
        with:
          record: true
          spec: cypress/integration/baseTest/specialist.spec.js
          # edge, firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  master-admin-elec-linux:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: master-admin-elec-linux
        uses: cypress-io/github-action@v2
        with:
          record: true
          spec: cypress/integration/baseTest/master.spec.js
          # edge, firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  mehanic-master-elec-linux:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: mehanic-master-elec-linux
        uses: cypress-io/github-action@v2
        with:
          record: true
          spec: cypress/integration/baseTest/masterMehanic.js
          # edge, firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  storage-master-elec-linux:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: storage-master-elec-linux
        uses: cypress-io/github-action@v2
        with:
          record: true
          spec: cypress/integration/baseTest/storage.spec.js
          # edge, firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        

  find-master-elec-linux:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: find-master-elec-linux
        uses: cypress-io/github-action@v2
        with:
          record: true
          spec: cypress/integration/baseTest/find.js
          # edge, firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     

  ppo-master-elec-linux:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: ppo-master-elec-linux
        uses: cypress-io/github-action@v2
        with:
          record: true
          spec: cypress/integration/baseTest/ppo.js
          # edge, firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

  menu-master-elec-linux:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: menu-master-elec-linux
        uses: cypress-io/github-action@v2
        with:
          record: true
          spec: cypress/integration/baseTest/menu.js
          # edge, firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     