name: E2E Testing
on: main
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      - name: Run CRA Build
        run: yarn build
      - name: Save Cypress artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: build
  e2e_tests:
    runs-on: ubuntu-latest
    needs: install
    container: cypress/browsers:node14.17.0-chrome91-ff89
    strategy:
      fail-fast: false
      matrix:
        containers: [homepage, contact-form, seo]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Cypress artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Cypress Test
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/${{ matrix.containers }}.js
          browser: chrome
          start: yarn start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}